# Generated by Django 2.2.17 on 2021-03-31 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate_my_walk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='length',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='views',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='comment',
            name='walk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rate_my_walk.WalkPage'),
        ),
        migrations.AddField(
            model_name='photo',
            name='walk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rate_my_walk.WalkPage'),
        ),
        migrations.AddField(
            model_name='rating',
            name='walk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rate_my_walk.WalkPage'),
        ),
        migrations.AddField(
            model_name='walkpage',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='page_image'),
        ),
        migrations.AddField(
            model_name='walkpage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='more_page_image'),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='desc',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='difficulty',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='end',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='enjoyment',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='start',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
