# Generated by Django 2.2.17 on 2021-03-26 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_walk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 11, 12, 20, 534737, tzinfo=utc)),
        ),
    ]
