# Generated by Django 2.2.17 on 2021-03-26 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_walk', '0002_auto_20210326_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 11, 13, 24, 361969, tzinfo=utc)),
        ),
    ]
