# Generated by Django 2.2.17 on 2021-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_walk', '0002_auto_20210331_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
