# Generated by Django 2.2.17 on 2021-03-26 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_walk', '0004_auto_20210326_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='length',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='views',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='rating',
            name='walk',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='rate_my_walk.WalkPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkpage',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='page_image'),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='desc',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='difficulty',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='walkpage',
            name='enjoyment',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
